development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: route-me_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: route-me_production
